name: Android → BrowserStack App Live
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: android-actions/setup-android@v3
      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug
      - name: Upload to BrowserStack App Live
        env:
          BS_USER: ${{ secrets.BROWSERSTACK_USERNAME }}
          BS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          APK_PATH=android/app/build/outputs/apk/debug/app-debug.apk
          curl -u "$BS_USER:$BS_KEY" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@$APK_PATH"